In [1]:
# Code Dependencies
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd

# ML Dependencies
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_squared_error

In [2]:
# Read the csv file into a pandas DataFrame
labs = pd.read_csv('../Resources/labs.csv')
labs.head()

,SUBJECT_ID,HADM_ID,Albumin,Anion Gap,Bicarbonate,"Bilirubin, Total",Chloride,"Chloride, Whole Blood",Creatinine,Glucose_Blood_Gas,...,PT,PTT,Phosphate,Platelet Count,Potassium,"Potassium, Whole Blood",Sodium,"Sodium, Whole Blood",Urea Nitrogen,White Blood Cells
0,2,163353.0,no test,no test,no test,normal,no test,no test,no test,no test,...,no test,no test,no test,abnormal,no test,no test,no test,no test,no test,abnormal
1,3,145834.0,abnormal,normal,normal,normal,abnormal,abnormal,abnormal,abnormal,...,abnormal,normal,abnormal,normal,abnormal,normal,normal,normal,abnormal,abnormal
2,4,185777.0,abnormal,normal,normal,abnormal,normal,no test,normal,no test,...,normal,normal,normal,normal,abnormal,no test,normal,no test,normal,delta
3,5,178980.0,no test,no test,no test,no test,no test,no test,no test,no test,...,no test,no test,no test,normal,no test,no test,no test,no test,no test,normal
4,6,107064.0,abnormal,abnormal,abnormal,normal,normal,abnormal,abnormal,abnormal,...,abnormal,abnormal,abnormal,normal,abnormal,normal,normal,normal,abnormal,normal

In [3]:
lived = pd.read_csv('../Resources/admissions_survived.csv')
lived.head()

,ROW_ID,SUBJECT_ID,HADM_ID,ADMITTIME,DISCHTIME,ADMISSION_TYPE,ADMISSION_LOCATION,DISCHARGE_LOCATION,INSURANCE,LANGUAGE,RELIGION,MARITAL_STATUS,ETHNICITY,EDREGTIME,EDOUTTIME,DIAGNOSIS,HOSPITAL_EXPIRE_FLAG,HAS_CHARTEVENTS_DATA,LENGTH_OF_STAY
0,21,22,165315,2196-04-09 12:26:00,2196-04-10 15:54:00,EMERGENCY,EMERGENCY ROOM ADMIT,DISC-TRAN CANCER/CHLDRN H,Private,NaN,UNOBTAINABLE,MARRIED,WHITE,2196-04-09 10:06:00,2196-04-09 13:24:00,BENZODIAZEPINE OVERDOSE,0,1,1.144444
1,22,23,152223,2153-09-03 07:15:00,2153-09-08 19:10:00,ELECTIVE,PHYS REFERRAL/NORMAL DELI,HOME HEALTH CARE,Medicare,NaN,CATHOLIC,MARRIED,WHITE,NaN,NaN,CORONARY ARTERY DISEASE\CORONARY ARTERY BYPASS...,0,1,5.496528
2,23,23,124321,2157-10-18 19:34:00,2157-10-25 14:00:00,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,HOME HEALTH CARE,Medicare,ENGL,CATHOLIC,MARRIED,WHITE,NaN,NaN,BRAIN MASS,0,1,6.768056
3,24,24,161859,2139-06-06 16:14:00,2139-06-09 12:48:00,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,HOME,Private,NaN,PROTESTANT QUAKER,SINGLE,WHITE,NaN,NaN,INTERIOR MYOCARDIAL INFARCTION,0,1,2.856944
4,25,25,129635,2160-11-02 02:06:00,2160-11-05 14:55:00,EMERGENCY,EMERGENCY ROOM ADMIT,HOME,Private,NaN,UNOBTAINABLE,MARRIED,WHITE,2160-11-02 01:01:00,2160-11-02 04:27:00,ACUTE CORONARY SYNDROME,0,1,3.534028

In [4]:
lived_df = pd.merge(lived,labs, on='HADM_ID')
lived_df.head()

,ROW_ID,SUBJECT_ID_x,HADM_ID,ADMITTIME,DISCHTIME,ADMISSION_TYPE,ADMISSION_LOCATION,DISCHARGE_LOCATION,INSURANCE,LANGUAGE,...,PT,PTT,Phosphate,Platelet Count,Potassium,"Potassium, Whole Blood",Sodium,"Sodium, Whole Blood",Urea Nitrogen,White Blood Cells
0,21,22,165315,2196-04-09 12:26:00,2196-04-10 15:54:00,EMERGENCY,EMERGENCY ROOM ADMIT,DISC-TRAN CANCER/CHLDRN H,Private,NaN,...,normal,normal,normal,normal,normal,no test,normal,no test,normal,normal
1,22,23,152223,2153-09-03 07:15:00,2153-09-08 19:10:00,ELECTIVE,PHYS REFERRAL/NORMAL DELI,HOME HEALTH CARE,Medicare,NaN,...,abnormal,abnormal,normal,abnormal,normal,normal,normal,normal,normal,delta
2,23,23,124321,2157-10-18 19:34:00,2157-10-25 14:00:00,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,HOME HEALTH CARE,Medicare,ENGL,...,normal,normal,normal,normal,normal,normal,normal,abnormal,normal,normal
3,24,24,161859,2139-06-06 16:14:00,2139-06-09 12:48:00,EMERGENCY,TRANSFER FROM HOSP/EXTRAM,HOME,Private,NaN,...,normal,normal,normal,normal,normal,no test,normal,no test,normal,normal
4,25,25,129635,2160-11-02 02:06:00,2160-11-05 14:55:00,EMERGENCY,EMERGENCY ROOM ADMIT,HOME,Private,NaN,...,normal,normal,normal,normal,normal,no test,normal,no test,abnormal,abnormal

In [5]:
lived_df.columns

Index(['ROW_ID', 'SUBJECT_ID_x', 'HADM_ID', 'ADMITTIME', 'DISCHTIME',
       'ADMISSION_TYPE', 'ADMISSION_LOCATION', 'DISCHARGE_LOCATION',
       'INSURANCE', 'LANGUAGE', 'RELIGION', 'MARITAL_STATUS', 'ETHNICITY',
       'EDREGTIME', 'EDOUTTIME', 'DIAGNOSIS', 'HOSPITAL_EXPIRE_FLAG',
       'HAS_CHARTEVENTS_DATA', 'LENGTH_OF_STAY', 'SUBJECT_ID_y', 'Albumin',
       'Anion Gap', 'Bicarbonate', 'Bilirubin, Total', 'Chloride',
       'Chloride, Whole Blood', 'Creatinine', 'Glucose_Blood_Gas',
       'Glucose_Chemistry', 'Hematocrit', 'Hematocrit, Calculated',
       'Hemoglobin_Blood_Gas', 'Hemoglobin_Hematology', 'INR(PT)', 'Lactate',
       'Magnesium', 'PT', 'PTT', 'Phosphate', 'Platelet Count', 'Potassium',
       'Potassium, Whole Blood', 'Sodium', 'Sodium, Whole Blood',
       'Urea Nitrogen', 'White Blood Cells'],
      dtype='object')

In [6]:
lived_df = lived_df.drop(['ROW_ID', 'SUBJECT_ID_x', 'HADM_ID', 'ADMITTIME', 'DISCHTIME', 'DISCHARGE_LOCATION',
                         'RELIGION', 'ETHNICITY', 'EDREGTIME', 'EDOUTTIME', 'HOSPITAL_EXPIRE_FLAG',
       'HAS_CHARTEVENTS_DATA', 'SUBJECT_ID_y', 'LANGUAGE'], axis = 1)

In [7]:
lived_df = pd.get_dummies(lived_df)
lived_df.head()

,LENGTH_OF_STAY,ADMISSION_TYPE_ELECTIVE,ADMISSION_TYPE_EMERGENCY,ADMISSION_TYPE_NEWBORN,ADMISSION_TYPE_URGENT,ADMISSION_LOCATION_** INFO NOT AVAILABLE **,ADMISSION_LOCATION_CLINIC REFERRAL/PREMATURE,ADMISSION_LOCATION_EMERGENCY ROOM ADMIT,ADMISSION_LOCATION_HMO REFERRAL/SICK,ADMISSION_LOCATION_PHYS REFERRAL/NORMAL DELI,...,"Sodium, Whole Blood_abnormal","Sodium, Whole Blood_no test","Sodium, Whole Blood_normal",Urea Nitrogen_abnormal,Urea Nitrogen_no test,Urea Nitrogen_normal,White Blood Cells_abnormal,White Blood Cells_delta,White Blood Cells_no test,White Blood Cells_normal
0,1.144444,0,1,0,0,0,0,1,0,0,...,0,1,0,0,0,1,0,0,0,1
1,5.496528,1,0,0,0,0,0,0,0,1,...,0,0,1,0,0,1,0,1,0,0
2,6.768056,0,1,0,0,0,0,0,0,0,...,1,0,0,0,0,1,0,0,0,1
3,2.856944,0,1,0,0,0,0,0,0,0,...,0,1,0,0,0,1,0,0,0,1
4,3.534028,0,1,0,0,0,0,1,0,0,...,0,1,0,1,0,0,1,0,0,0

In [8]:
# assignment and reshaping of data
data = lived_df.drop(["LENGTH_OF_STAY"], axis=1)
target = lived_df["LENGTH_OF_STAY"].values.reshape(-1, 1)

print(f"data shape: {data.shape}")
print(f"target shape: {target.shape}")

data shape: (52294, 14127)
target shape: (52294, 1)

In [9]:
# Create test and train sets
X_train, X_test, y_train, y_test = train_test_split(data, target, random_state=42)

print(f"----train & test sizes-----")
print(f"train size: {len(X_train)}, keys: {len(X_train.keys())}")
print(f"test size: {len(X_test)}, keys: {len(X_test.keys())}")

----train & test sizes-----
train size: 39220, keys: 14127
test size: 13074, keys: 14127

In [10]:
# Modeling
model = RandomForestRegressor(n_estimators=200)

In [11]:
model.fit(X_train, y_train.ravel())

RandomForestRegressor(bootstrap=True, criterion='mse', max_depth=None,
           max_features='auto', max_leaf_nodes=None,
           min_impurity_decrease=0.0, min_impurity_split=None,
           min_samples_leaf=1, min_samples_split=2,
           min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=1,
           oob_score=False, random_state=None, verbose=0, warm_start=False)

In [12]:
# create the predictions
predictions = model.predict(X_test)
predictions

array([ 7.39842014, 28.43516319, 12.18727431, ..., 10.47728819,
       10.55703125,  6.75813889])

In [14]:
MSE = mean_squared_error(y_test, predictions)
r2 = model.score(X_test, y_test)

print(f"MSE: {MSE}, R2: {r2}")

MSE: 87.78553001155943, R2: 0.4188675617314901

In [16]:
# create a dataframe of the importance features sorted
feature_names = X_train.columns
importances = sorted(zip(model.feature_importances_, feature_names), reverse=True)
importance_df = pd.DataFrame(importances)
importance_df = importance_df.rename(columns={0:"Importance",1:"Feature"})
importance_df.to_csv('rf_lived_feature_importance')
importance_df

       Importance                                            Feature
0        0.111865                                  Phosphate_no test
1        0.056674                                   Albumin_abnormal
2        0.055111                                  DIAGNOSIS_NEWBORN
3        0.050507                             ADMISSION_TYPE_NEWBORN
4        0.038768                          Glucose_Blood_Gas_no test
5        0.029413                           Bilirubin, Total_no test
6        0.017508                                  Anion Gap_no test
7        0.012493        DIAGNOSIS_CROHN'S DISEASE;ABDOMINAL FISTULA
8        0.011507                             Urea Nitrogen_abnormal
9        0.008292                      Hemoglobin_Blood_Gas_abnormal
10       0.008184                              DIAGNOSIS_PREMATURITY
11       0.007983       ADMISSION_LOCATION_CLINIC REFERRAL/PREMATURE
12       0.006897                                    Lactate_no test
13       0.006450                                   Phosphate_normal
14       0.006142                                Creatinine_abnormal
15       0.006097                                 INSURANCE_Medicaid
16       0.006023                                   Magnesium_normal
17       0.005953                       Hemoglobin_Blood_Gas_no test
18       0.005862                      Hematocrit, Calculated_normal
19       0.005757                                 Phosphate_abnormal
20       0.005712                         White Blood Cells_abnormal
21       0.005471                           White Blood Cells_normal
22       0.005401                     Potassium, Whole Blood_no test
23       0.005071                              MARITAL_STATUS_SINGLE
24       0.005041                                 Bicarbonate_normal
25       0.004939                         Glucose_Chemistry_abnormal
26       0.004917                                  Creatinine_normal
27       0.004908                                  INSURANCE_Private
28       0.004834                               Bicarbonate_abnormal
29       0.004707                     Hematocrit, Calculated_no test
...           ...                                                ...
14097    0.000000       DIAGNOSIS_? SUBDURAL HEMATOMA-SPINE FRACTURE
14098    0.000000                          DIAGNOSIS_? SPINAL INJURY
14099    0.000000                            DIAGNOSIS_? SEPTIC KNEE
14100    0.000000                                 DIAGNOSIS_? SEPSIS
14101    0.000000                         DIAGNOSIS_? PYELONEPHRITIS
14102    0.000000    DIAGNOSIS_? PULMONARY EMBOLUS WITH DESATURATION
14103    0.000000                       DIAGNOSIS_? ISCHEMIC COLITIS
14104    0.000000                              DIAGNOSIS_? INGESTION
14105    0.000000               DIAGNOSIS_? GALLSTONES; PANCREATITIS
14106    0.000000                            DIAGNOSIS_? BRAIN TUMOR
14107    0.000000                             DIAGNOSIS_? BABESIOSIS
14108    0.000000                DIAGNOSIS_4TH VENTRICULAR TUMOR/SDA
14109    0.000000                     DIAGNOSIS_3RD. DEGREE AV BLOCK
14110    0.000000           DIAGNOSIS_3RD DEGREE HEART BLOCK SARCOID
14111    0.000000                          DIAGNOSIS_38 WK INDUCTION
14112    0.000000  DIAGNOSIS_37 WEEKS;ATRIAL FIBRILLATION;TELEMET...
14113    0.000000     DIAGNOSIS_34 WEEKS PLACENTA CREDA AND ABD PAIN
14114    0.000000  DIAGNOSIS_3 VESSEL DISEASE REQUIRING CORONARY ...
14115    0.000000                  DIAGNOSIS_25 WEEKS ABDOMINAL PAIN
14116    0.000000           DIAGNOSIS_24 WEEKS PREGNANT;KIDNEY STONE
14117    0.000000              DIAGNOSIS_+MIBI;CATH;DEHYDRATION\CATH
14118    0.000000                         DIAGNOSIS_+ETT;ANGINA\CATH
14119    0.000000                               DIAGNOSIS_+ TROPONIN
14120    0.000000         DIAGNOSIS_+ ETT\LEFT HEART CATHETERIZATION
14121    0.000000                                   DIAGNOSIS_ STEMI
14122    0.000000             DIAGNOSIS_ OPEN WOUND TO THE CHEST/SDA
14123    0.000000                                 DIAGNOSIS_ HYPOXIA
14124    0.000000  DIAGNOSIS_ CORONARY ARTERY DISEASE & MITRAL RE...
14125    0.000000                                     DIAGNOSIS_ CAS
14126    0.000000  DIAGNOSIS_        MITRAL STENOSIS\MITRAL VALVE...

[14127 rows x 2 columns]